// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"time"
	"github.com/lib/pq"
)

const TableNameStellarLendingAction = "stellar_lending_actions"

// StellarLendingAction mapped from table <stellar_lending_actions>
type StellarLendingAction struct {
	EventID         string    `gorm:"column:event_id;primaryKey" json:"event_id"`
	PoolContractID  string    `gorm:"column:pool_contract_id;not null" json:"pool_contract_id"`
	UserType        string    `gorm:"column:user_type;not null" json:"user_type"`
	UserAccount     string    `gorm:"column:user_account;not null" json:"user_account"`
	ActionType      string    `gorm:"column:action_type;not null" json:"action_type"`
	TokenType       string    `gorm:"column:token_type" json:"token_type"`
	TokenAccount    string    `gorm:"column:token_account" json:"token_account"`
	RequestAmount   string    `gorm:"column:request_amount" json:"request_amount"`
	BtokenAmount    string    `gorm:"column:btoken_amount" json:"btoken_amount"`
	BtokenType      string    `gorm:"column:btoken_type" json:"btoken_type"`
	BtokenAccount   string    `gorm:"column:btoken_account" json:"btoken_account"`
	DtokenAmount    string    `gorm:"column:dtoken_amount" json:"dtoken_amount"`
	DtokenType      string    `gorm:"column:dtoken_type" json:"dtoken_type"`
	DtokenAccount   string    `gorm:"column:dtoken_account" json:"dtoken_account"`
	ParsedJSON      string    `gorm:"column:parsed_json;type:jsonb" json:"parsed_json"`
	Ledger          int64     `gorm:"column:ledger" json:"ledger"`
	LedgerClosedAt  time.Time     `gorm:"column:ledger_closed_at" json:"ledger_closed_at"`
	Topic           pq.StringArray    `gorm:"column:topic;type:text[]" json:"topic"`
	Value           string    `gorm:"column:value" json:"value"`
	TransactionHash string    `gorm:"column:transaction_hash" json:"transaction_hash"`
	ProcessTime     time.Time     `gorm:"column:process_time" json:"process_time"`
	BlockDate       time.Time `gorm:"column:block_date" json:"block_date"`
}

// TableName StellarLendingAction's table name
func (*StellarLendingAction) TableName() string {
	return TableNameStellarLendingAction
}
