name: dex-pipeline  # required, no space or special chars allowed, must be consistent with the pipeline folder name
source:
  startBlock: 53710592
  schema: "stellar_mainnet"
  sourceDB: PG_EVM_PROD
destination:
  destinationDB: PG_EVM_PROD
  schema: "defi"
metadata:
  metadataDB: PG_EVM_PROD
  schema: "stellar_zrunner_metadata"
blockHandlers:
  - handler: HandleBlock
